CREATE TABLE Movies (
    MovieID INT PRIMARY KEY IDENTITY(1,1),
    Title NVARCHAR(200) NOT NULL,
    Genre NVARCHAR(50),
    DurationMin INT
);

CREATE TABLE Halls (
    HallID INT PRIMARY KEY IDENTITY(1,1),
    HallName NVARCHAR(50) NOT NULL,
    TotalSeats INT NOT NULL
);

CREATE TABLE Shows (
    ShowID INT PRIMARY KEY IDENTITY(1,1),
    MovieID INT FOREIGN KEY REFERENCES Movies(MovieID),
    HallID INT FOREIGN KEY REFERENCES Halls(HallID),
    StartTime DATETIME NOT NULL,
    Price DECIMAL(10, 2) NOT NULL
);

CREATE TABLE Customers (
    CustomerID INT PRIMARY KEY IDENTITY(1,1),
    FullName NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100) UNIQUE
);

CREATE TABLE Tickets (
    TicketID INT PRIMARY KEY IDENTITY(1,1),
    ShowID INT FOREIGN KEY REFERENCES Shows(ShowID),
    CustomerID INT FOREIGN KEY REFERENCES Customers(CustomerID),
    SeatNumber INT NOT NULL,
    BookingDate DATETIME DEFAULT GETDATE()
);
